// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonnalApi.Data;

#nullable disable

namespace PersonnalApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonnalApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PersonnalApi.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("PersonnalApi.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gym")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("PersonnalApi.Models.PokeGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PokeGames");
                });

            modelBuilder.Entity("PersonnalApi.Models.PokeGameCategory", b =>
                {
                    b.Property<int>("PokeGameId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("PokeGameId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PokaGameCategories");
                });

            modelBuilder.Entity("PersonnalApi.Models.PokeGameOwner", b =>
                {
                    b.Property<int>("PokeGameId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("PokeGameId", "OwnerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("PokaGameOwners");
                });

            modelBuilder.Entity("PersonnalApi.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PokeGameId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PokeGameId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("PersonnalApi.Models.Reviewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reviewers");
                });

            modelBuilder.Entity("PersonnalApi.Models.Owner", b =>
                {
                    b.HasOne("PersonnalApi.Models.Country", "Country")
                        .WithMany("Owners")
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PersonnalApi.Models.PokeGameCategory", b =>
                {
                    b.HasOne("PersonnalApi.Models.Category", "Category")
                        .WithMany("pokeGameCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonnalApi.Models.PokeGame", "PokeGame")
                        .WithMany("pokeGameCategories")
                        .HasForeignKey("PokeGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("PokeGame");
                });

            modelBuilder.Entity("PersonnalApi.Models.PokeGameOwner", b =>
                {
                    b.HasOne("PersonnalApi.Models.Owner", "Owner")
                        .WithMany("pokeGameOwners")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonnalApi.Models.PokeGame", "PokeGame")
                        .WithMany("pokeGameOwners")
                        .HasForeignKey("PokeGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("PokeGame");
                });

            modelBuilder.Entity("PersonnalApi.Models.Review", b =>
                {
                    b.HasOne("PersonnalApi.Models.PokeGame", "PokeGame")
                        .WithMany("Reviews")
                        .HasForeignKey("PokeGameId");

                    b.HasOne("PersonnalApi.Models.Reviewer", "Reviewer")
                        .WithMany("reviews_id")
                        .HasForeignKey("ReviewerId");

                    b.Navigation("PokeGame");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("PersonnalApi.Models.Category", b =>
                {
                    b.Navigation("pokeGameCategories");
                });

            modelBuilder.Entity("PersonnalApi.Models.Country", b =>
                {
                    b.Navigation("Owners");
                });

            modelBuilder.Entity("PersonnalApi.Models.Owner", b =>
                {
                    b.Navigation("pokeGameOwners");
                });

            modelBuilder.Entity("PersonnalApi.Models.PokeGame", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("pokeGameCategories");

                    b.Navigation("pokeGameOwners");
                });

            modelBuilder.Entity("PersonnalApi.Models.Reviewer", b =>
                {
                    b.Navigation("reviews_id");
                });
#pragma warning restore 612, 618
        }
    }
}
